project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550"
  page-footer:
    left: "Emma Witanowski, Hayden Chu, & Jack Chen©, 2024"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  back-to-top-navigation: true
  page-navigation: true
  search: true
  reader-mode: true
        
  navbar:
    search: true
    title: false
    logo: "images/logo_python.png"
    background: "#d0c7e1"
    logo-alt: "N/A"
    left:
      - href: Introduction.ipynb
        text: Introduction
      - href: AnalysisResults/Data_Gather.ipynb
        text: Data Gathering
      - text: Analysis & Results
        menu:
          - text: Density Map of Assaults
            href: AnalysisResults/Density.ipynb
          - text: Fishnet Grid
            href: AnalysisResults/Fishnet.ipynb
          - text: Distribution of Assaults
            href: AnalysisResults/DistributionofAssaults.ipynb
          - text: Visualizing Risk Factors 
            href: AnalysisResults/VisualizingRiskFactors.ipynb
          - text: Local Spatial Autocorrelation
            href: AnalysisResults/LocalSpatialAutocorrelation.ipynb
          - text: Clustering Risk Factors
            href: AnalysisResults/Clustering.ipynb
          - text: K-Means
            href: AnalysisResults/KMeans.ipynb
          - text: Poisson Modelling
            href: AnalysisResults/Untitled.ipynb
          - text: Predicted Assault Cases
            href: AnalysisResults/Predicted.ipynb
          - text: Residuals
            href: AnalysisResults/Residuals.ipynb
          - text: Correlation Matrix
            href: AnalysisResults/CorMatrix.ipynb
      - href: Concluding_Thoughts.ipynb
        text: Concluding Thoughts

format:
  html:
    highlight-style: solarized
    theme: flatly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
